package org.mobicents.slee.resource.jdbc.event;

import java.sql.SQLException;
import java.sql.Statement;

/**
 * 
 * @author martins
 * 
 */
public class StatementSQLExceptionEventImpl extends AbstractStatementEvent
		implements StatementSQLExceptionEvent {

	/**
	 * 
	 */
	private final SQLException sqlException;

	/**
	 * 
	 * @param autoGeneratedKeys
	 * @param columnIndexes
	 * @param columnNames
	 * @param sql
	 * @param statement
	 * @param sqlException
	 */
	public StatementSQLExceptionEventImpl(Integer autoGeneratedKeys,
			int[] columnIndexes, String[] columnNames, String sql,
			Statement statement, SQLException sqlException) {
		super(autoGeneratedKeys, columnIndexes, columnNames, sql, statement);
		this.sqlException = sqlException;
	}

	@Override
	public SQLException getSQLException() {
		return sqlException;
	}

}
