/*
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2017, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:44:00 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee.event;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobicents.slee.container.component.deployment.jaxb.slee.event package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobicents.slee.container.component.deployment.jaxb.slee.event
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventJar }
     * 
     */
    public EventJar createEventJar() {
        return new EventJar();
    }

    /**
     * Create an instance of {@link EventClassName }
     * 
     */
    public EventClassName createEventClassName() {
        return new EventClassName();
    }

    /**
     * Create an instance of {@link EventDefinition }
     * 
     */
    public EventDefinition createEventDefinition() {
        return new EventDefinition();
    }

    /**
     * Create an instance of {@link EventTypeVendor }
     * 
     */
    public EventTypeVendor createEventTypeVendor() {
        return new EventTypeVendor();
    }

    /**
     * Create an instance of {@link EventTypeName }
     * 
     */
    public EventTypeName createEventTypeName() {
        return new EventTypeName();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link EventTypeVersion }
     * 
     */
    public EventTypeVersion createEventTypeVersion() {
        return new EventTypeVersion();
    }

}
