package org.mobicents.persistencera.test;

// Generated 2007-04-29 20:11:03 by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "pra", uniqueConstraints = {})
public class Test implements java.io.Serializable {

	// Fields

	private int id;

	private String value;

	// Constructors

	/** default constructor */
	public Test() {
	}

	/** full constructor */
	public Test(int id, String value) {
		this.id = id;
		this.value = value;
	}

	// Property accessors
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VALUE", unique = false, nullable = false, insertable = true, updatable = true, length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
