/*
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2017, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:43:57 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee11.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "resourceAdaptorClass",
    "resourceAdaptorUsageParametersInterface"
})
@XmlRootElement(name = "resource-adaptor-classes")
public class ResourceAdaptorClasses {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "resource-adaptor-class", required = true)
    protected ResourceAdaptorClass resourceAdaptorClass;
    @XmlElement(name = "resource-adaptor-usage-parameters-interface")
    protected ResourceAdaptorUsageParametersInterface resourceAdaptorUsageParametersInterface;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the resourceAdaptorClass property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorClass }
     *     
     */
    public ResourceAdaptorClass getResourceAdaptorClass() {
        return resourceAdaptorClass;
    }

    /**
     * Sets the value of the resourceAdaptorClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorClass }
     *     
     */
    public void setResourceAdaptorClass(ResourceAdaptorClass value) {
        this.resourceAdaptorClass = value;
    }

    /**
     * Gets the value of the resourceAdaptorUsageParametersInterface property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorUsageParametersInterface }
     *     
     */
    public ResourceAdaptorUsageParametersInterface getResourceAdaptorUsageParametersInterface() {
        return resourceAdaptorUsageParametersInterface;
    }

    /**
     * Sets the value of the resourceAdaptorUsageParametersInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorUsageParametersInterface }
     *     
     */
    public void setResourceAdaptorUsageParametersInterface(ResourceAdaptorUsageParametersInterface value) {
        this.resourceAdaptorUsageParametersInterface = value;
    }

}
