//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:43:57 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee11.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "configPropertyName",
    "configPropertyType",
    "configPropertyValue"
})
@XmlRootElement(name = "config-property")
public class ConfigProperty {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "config-property-name", required = true)
    protected ConfigPropertyName configPropertyName;
    @XmlElement(name = "config-property-type", required = true)
    protected ConfigPropertyType configPropertyType;
    @XmlElement(name = "config-property-value")
    protected ConfigPropertyValue configPropertyValue;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the configPropertyName property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigPropertyName }
     *     
     */
    public ConfigPropertyName getConfigPropertyName() {
        return configPropertyName;
    }

    /**
     * Sets the value of the configPropertyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigPropertyName }
     *     
     */
    public void setConfigPropertyName(ConfigPropertyName value) {
        this.configPropertyName = value;
    }

    /**
     * Gets the value of the configPropertyType property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigPropertyType }
     *     
     */
    public ConfigPropertyType getConfigPropertyType() {
        return configPropertyType;
    }

    /**
     * Sets the value of the configPropertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigPropertyType }
     *     
     */
    public void setConfigPropertyType(ConfigPropertyType value) {
        this.configPropertyType = value;
    }

    /**
     * Gets the value of the configPropertyValue property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigPropertyValue }
     *     
     */
    public ConfigPropertyValue getConfigPropertyValue() {
        return configPropertyValue;
    }

    /**
     * Sets the value of the configPropertyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigPropertyValue }
     *     
     */
    public void setConfigPropertyValue(ConfigPropertyValue value) {
        this.configPropertyValue = value;
    }

}
