package javax.slee;

/**
 * This interface is implemented by activity end events generated by the SLEE
 * when an activity ends.
 * <p>
 * The event type name of activity end events is "<code>javax.slee.ActivityEndEvent</code>".
 */
public interface ActivityEndEvent {}

