/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:43:58 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee11.profile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobicents.slee.container.component.deployment.jaxb.slee11.profile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobicents.slee.container.component.deployment.jaxb.slee11.profile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CmpField }
     * 
     */
    public CmpField createCmpField() {
        return new CmpField();
    }

    /**
     * Create an instance of {@link LocaleVariant }
     * 
     */
    public LocaleVariant createLocaleVariant() {
        return new LocaleVariant();
    }

    /**
     * Create an instance of {@link RangeMatch }
     * 
     */
    public RangeMatch createRangeMatch() {
        return new RangeMatch();
    }

    /**
     * Create an instance of {@link EnvEntryType }
     * 
     */
    public EnvEntryType createEnvEntryType() {
        return new EnvEntryType();
    }

    /**
     * Create an instance of {@link LocaleLanguage }
     * 
     */
    public LocaleLanguage createLocaleLanguage() {
        return new LocaleLanguage();
    }

    /**
     * Create an instance of {@link Collator }
     * 
     */
    public Collator createCollator() {
        return new Collator();
    }

    /**
     * Create an instance of {@link LongestPrefixMatch }
     * 
     */
    public LongestPrefixMatch createLongestPrefixMatch() {
        return new LongestPrefixMatch();
    }

    /**
     * Create an instance of {@link LibraryVendor }
     * 
     */
    public LibraryVendor createLibraryVendor() {
        return new LibraryVendor();
    }

    /**
     * Create an instance of {@link ProfileManagementInterface }
     * 
     */
    public ProfileManagementInterface createProfileManagementInterface() {
        return new ProfileManagementInterface();
    }

    /**
     * Create an instance of {@link EnvEntryName }
     * 
     */
    public EnvEntryName createEnvEntryName() {
        return new EnvEntryName();
    }

    /**
     * Create an instance of {@link ProfileSpecName }
     * 
     */
    public ProfileSpecName createProfileSpecName() {
        return new ProfileSpecName();
    }

    /**
     * Create an instance of {@link EnvEntry }
     * 
     */
    public EnvEntry createEnvEntry() {
        return new EnvEntry();
    }

    /**
     * Create an instance of {@link ProfileSpec }
     * 
     */
    public ProfileSpec createProfileSpec() {
        return new ProfileSpec();
    }

    /**
     * Create an instance of {@link ProfileCmpInterface }
     * 
     */
    public ProfileCmpInterface createProfileCmpInterface() {
        return new ProfileCmpInterface();
    }

    /**
     * Create an instance of {@link Not }
     * 
     */
    public Not createNot() {
        return new Not();
    }

    /**
     * Create an instance of {@link QueryOptions }
     * 
     */
    public QueryOptions createQueryOptions() {
        return new QueryOptions();
    }

    /**
     * Create an instance of {@link ProfileClasses }
     * 
     */
    public ProfileClasses createProfileClasses() {
        return new ProfileClasses();
    }

    /**
     * Create an instance of {@link ProfileTableInterfaceName }
     * 
     */
    public ProfileTableInterfaceName createProfileTableInterfaceName() {
        return new ProfileTableInterfaceName();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link EnvEntryValue }
     * 
     */
    public EnvEntryValue createEnvEntryValue() {
        return new EnvEntryValue();
    }

    /**
     * Create an instance of {@link Compare }
     * 
     */
    public Compare createCompare() {
        return new Compare();
    }

    /**
     * Create an instance of {@link LibraryRef }
     * 
     */
    public LibraryRef createLibraryRef() {
        return new LibraryRef();
    }

    /**
     * Create an instance of {@link LibraryVersion }
     * 
     */
    public LibraryVersion createLibraryVersion() {
        return new LibraryVersion();
    }

    /**
     * Create an instance of {@link IndexHint }
     * 
     */
    public IndexHint createIndexHint() {
        return new IndexHint();
    }

    /**
     * Create an instance of {@link SecurityPermissionSpec }
     * 
     */
    public SecurityPermissionSpec createSecurityPermissionSpec() {
        return new SecurityPermissionSpec();
    }

    /**
     * Create an instance of {@link QueryParameter }
     * 
     */
    public QueryParameter createQueryParameter() {
        return new QueryParameter();
    }

    /**
     * Create an instance of {@link ProfileUsageParametersInterface }
     * 
     */
    public ProfileUsageParametersInterface createProfileUsageParametersInterface() {
        return new ProfileUsageParametersInterface();
    }

    /**
     * Create an instance of {@link HasPrefix }
     * 
     */
    public HasPrefix createHasPrefix() {
        return new HasPrefix();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link ProfileSpecVersion }
     * 
     */
    public ProfileSpecVersion createProfileSpecVersion() {
        return new ProfileSpecVersion();
    }

    /**
     * Create an instance of {@link ProfileSpecVendor }
     * 
     */
    public ProfileSpecVendor createProfileSpecVendor() {
        return new ProfileSpecVendor();
    }

    /**
     * Create an instance of {@link UsageParameter }
     * 
     */
    public UsageParameter createUsageParameter() {
        return new UsageParameter();
    }

    /**
     * Create an instance of {@link ProfileSpecJar }
     * 
     */
    public ProfileSpecJar createProfileSpecJar() {
        return new ProfileSpecJar();
    }

    /**
     * Create an instance of {@link Or }
     * 
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link LocaleCountry }
     * 
     */
    public LocaleCountry createLocaleCountry() {
        return new LocaleCountry();
    }

    /**
     * Create an instance of {@link CmpFieldName }
     * 
     */
    public CmpFieldName createCmpFieldName() {
        return new CmpFieldName();
    }

    /**
     * Create an instance of {@link ProfileLocalInterface }
     * 
     */
    public ProfileLocalInterface createProfileLocalInterface() {
        return new ProfileLocalInterface();
    }

    /**
     * Create an instance of {@link ProfileAbstractClass }
     * 
     */
    public ProfileAbstractClass createProfileAbstractClass() {
        return new ProfileAbstractClass();
    }

    /**
     * Create an instance of {@link LibraryName }
     * 
     */
    public LibraryName createLibraryName() {
        return new LibraryName();
    }

    /**
     * Create an instance of {@link ProfileManagementInterfaceName }
     * 
     */
    public ProfileManagementInterfaceName createProfileManagementInterfaceName() {
        return new ProfileManagementInterfaceName();
    }

    /**
     * Create an instance of {@link And }
     * 
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link ProfileLocalInterfaceName }
     * 
     */
    public ProfileLocalInterfaceName createProfileLocalInterfaceName() {
        return new ProfileLocalInterfaceName();
    }

    /**
     * Create an instance of {@link SecurityPermissions }
     * 
     */
    public SecurityPermissions createSecurityPermissions() {
        return new SecurityPermissions();
    }

    /**
     * Create an instance of {@link ProfileSpecRef }
     * 
     */
    public ProfileSpecRef createProfileSpecRef() {
        return new ProfileSpecRef();
    }

    /**
     * Create an instance of {@link ProfileAbstractClassName }
     * 
     */
    public ProfileAbstractClassName createProfileAbstractClassName() {
        return new ProfileAbstractClassName();
    }

    /**
     * Create an instance of {@link CollatorAlias }
     * 
     */
    public CollatorAlias createCollatorAlias() {
        return new CollatorAlias();
    }

    /**
     * Create an instance of {@link ProfileTableInterface }
     * 
     */
    public ProfileTableInterface createProfileTableInterface() {
        return new ProfileTableInterface();
    }

    /**
     * Create an instance of {@link ProfileCmpInterfaceName }
     * 
     */
    public ProfileCmpInterfaceName createProfileCmpInterfaceName() {
        return new ProfileCmpInterfaceName();
    }

    /**
     * Create an instance of {@link ProfileHints }
     * 
     */
    public ProfileHints createProfileHints() {
        return new ProfileHints();
    }

    /**
     * Create an instance of {@link ProfileUsageParametersInterfaceName }
     * 
     */
    public ProfileUsageParametersInterfaceName createProfileUsageParametersInterfaceName() {
        return new ProfileUsageParametersInterfaceName();
    }

}
