[[_configuration_and_running]]
= Configuring and Running {this-platform}  JAIN SLEE

[[_server_profiles]]
== Server Profiles

{this-platform} JAIN SLEE reuses {jee-platform} server modes to expose different configurations for different needs. {jee-platform} can be booted in two different modes. A managed domain allows you to run and manage a multi-server topology. Alternatively, you can run a standalone server instance.

Standalone Server::

  For many use cases, the centralized management capability available via a managed domain is not necessary. For these use cases, a {jee-platform} instance can be run as a `standalone server`. A standalone server instance is an independent process, much like an JBoss Application Server 3, 4, 5, or 6 instance is. Standalone instances can be launched via the standalone.sh or standalone.bat launch scripts.
::
  If more than one standalone instance is launched and multi-server management is desired, it is the user's responsibility to coordinate management across the servers. For example, to deploy an application across all of the standalone servers, the user would need to individually deploy the application on each server.
::
  It is perfectly possible to launch multiple standalone server instances and have them form an HA cluster, just like it was possible with JBoss Application Server 3, 4, 5 and 6.

Managed Domain::
  One of the primary new features of {jee-platform} is the ability to manage multiple {jee-platform} instances from a single control point. A collection of such servers is referred to as the members of a `domain` with a single Domain Controller process acting as the central management control point. All of the {jee-platform} instances in the domain share a common management policy, with the Domain Controller acting to ensure that each server is configured according to that policy. Domains can span multiple physical (or virtual) machines, with all {jee-platform} instances on a given host under the control of a special Host Controller process. One Host Controller instance is configured to act as the central Domain Controller. The Host Controller on each host interacts with the Domain Controller to control the lifecycle of the application server instances running on its host and to assist the Domain Controller in managing them.

Profiles can be selected when starting the server, see <<_running>> for detailed instructions.

[[_running]]
== Running {this-platform} JAIN SLEE

Starting or stopping {this-platform} JAIN SLEE is no different than starting or stopping {jee-platform}

=== Starting

Once installed, you can run server(s) by executing the standalone.sh (Unix) or standalone.bat (Microsoft Windows) startup scripts in the [path]_<install_directory>/bin_ directory (on Unix or Windows).

[[_starting_paramaters]]
==== Starting Parameters

Server Config::
  If you choose to start your server with one of the other provided configurations, they can be accessed by passing the --server-config argument with the server-config file to be used.

----
$JBOSS_HOME/bin/standalone.sh --server-config=standalone-full-ha.xml
----

IMPORTANT: If not specified the default config is used.

IP / Host::
  To specify the IP/Host which the server binds, use `-b=IP`, for instance, to use the 192.168.0.1 IP then start the server with `-b=192.168.0.1`

----
$JBOSS_HOME/bin/standalone.sh -b=192.168.0.1
----

IMPORTANT: If not specified then 127.0.0.1 is used.

More details on command line parameters you can read here:
https://docs.jboss.org/author/display/WFLY10/Command+line+parameters

=== Stopping

You can shut down the server(s) by executing

----
$JBOSS_HOME/bin/jboss-cli.sh --connect command=:shutdown
----

Or you can stop server with Ctrl + C.

Note that if you properly stop the server, you will see the following three lines as the last output in the Unix terminal or Command Prompt:

----
14:57:43,783 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0050: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) stopped in 403ms
----

More details on command line interface you can read here:
https://docs.jboss.org/author/display/WFLY10/Admin+Guide#AdminGuide-CommandLineInterface


[[_configuration]]
== Configuring {this-platform} JAIN SLEE

JAIN SLEE is deployed as {jee-platform} extension and is configured through an standalone.xml. This file is located at [path]_$JBOSS_HOME/standalone/configuration_.

WARNING: This configuration greatly affects performance or correctness of the container behavior.
This is for advanced users that know the internals of the container.

:leveloffset: +1

include::Section-EventContext_Factory_Configuration.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Event_Router_Configuration.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Timer_Facility_Configuration.adoc[]

:leveloffset: -1

[[_profiles_configuration]]
=== Configuring JAIN SLEE Profiles

JAIN SLEE Profiles is a component used to store data, usually related with a user and/or service profile.
JAIN SLEE maps JAIN SLEE Profiles to a Java Persistence API (JPA) Datasource, through Hibernate.

There is configuration for JAIN SLEE Profiles provided as JBoss Microcontainer Beans:

[source,xml]
----
<mbean name="H2DBConfig">
    <property name="persistProfiles" value="true" />
    <property name="clusteredProfiles" value="false" />
    <property name="hibernateDatasource" value="java:jboss/datasources/ExampleDS" />
    <property name="hibernateDialect" value="org.hibernate.dialect.H2Dialect" />
</mbean>
<mbean name="PostgreDBConfig">
    <property name="persistProfiles" value="true" />
    <property name="clusteredProfiles" value="false" />
    <property name="hibernateDatasource" value="java:jboss/datasources/PostgreDS" />
    <property name="hibernateDialect" value="org.hibernate.dialect.PostgreSQL94Dialect" />
    <property name="datasourceServiceName" value="PostgreDS" />
</mbean>
<mbean name="ProfileManagement">
    <property name="dbConfigMBean" value="PostgreDBConfig" />
</mbean>
----

IMPORTANT: Configurations can be changed, or new ones can be added.
For new ones, ensure that the name attribute of the bean element is unique.

.JAIN SLEE Profiles Bean Configuration
[cols="1,1,1", frame="all", options="header"]
|===
| Property Name | Property Type | Description
| persistProfiles | boolean | If true, profile changes are persisted into the data source.
| clusteredProfiles | boolean | If true, then the container is aware there is a shared data source and that updates may be done by other nodes (for example, deletion of a JAIN SLEE profile table).
| hibernateDatasource | String | The name of the Java Datasource deployed in the WildFly.
| hibernateDialect | String | The java class name of the hibernate dialect to use, related with
 the selected datasource.
| datasourceServiceName | String | The pool name of Datasource from WildFly configuration.
|===


=== Other Configurations

Other JAIN SLEE runtime configuration is done through the following JBoss Microcontainer Bean:

[source,xml]
----

<mbean name="MobicentsManagement">
	<property name="entitiesRemovalDelay" value="1" />
	<property name="initializeReferenceDataTypesWithNull" value="true" />
</mbean>
----

.Other JAIN SLEE Configurations
[cols="1,1,1", frame="all", options="header"]
|===
| Property Name | Property Type | Description
| entitiesRemovalDelay | int | The number of minutes before the container forces the ending of SBB entities from a service being deactivated.
| initializeReferenceDataTypesWithNull | boolean | The flag for initializing SBB CMP fields with Numeric Reference Data types to 0 (false) or null (true).
|===

This configuration can be changed with the container running with JMX.
Note that such configuration changes are not persisted.

To change the configuraton, use the JMX MBean named [app]`org.mobicents.slee:service=MobicentsManagement`, which provides getters and setters to change each property defined in the persistent configuration that is configurable with the container running.
The JConsole can be used to use this MBean, as described in <<_management_jconsole>>.

=== Logging Configuration

Logging configuration is documented in section <<_global_logging_config>>

[[_congestion_control_configuration_]]
=== Congestion Control Configuration

Congesture Control feature configuration is documented in section <<_congestion_control_configuration>>
