[[_management]]
= Managing {this-platform}  JAIN SLEE


[[_management_components]]
== Managing JAIN SLEE Components

:leveloffset: +1

include::Section-Management_Persistent_File_Deployer.adoc[]

:leveloffset: -1

== Management Consoles

[[_management_jconsole]]
=== JConsole

{jee-platform} provides a script `jconsole.sh` that starts JConsole tool that gives quick access to all MBeans registered in the server, which includes the ones defined by the JAIN SLEE 1.1 specification. This script adds {jee-platform} CLI tab for access to {jee-platform} server information. Also you can acces to all MBeans in MBeans tab.

----
$JBOSS_HOME/bin/jconsole.sh
----

MBeans in the domain `javax.slee` are all standard JAIN SLEE 1.1 MBeans, while the ones in the domain `org.mobicents.slee` are proprietary to {this-platform}  JAIN SLEE.
The following ones are of particular interest: 

`org.mobicents.slee:service=MobicentsManagement`::
  the MBean which can be used to make non persistent changes to the server configuration, in runtime.
  The operation `dumpContainerState` displays a textual snapshot of the server's state, which can be used to quickly look for memory leaks or other debug/profiling related tasks.

`org.mobicents.slee:name=DeployerMBean`::
  the MBean allows interaction with the persistent deployable unit deployer.
  The operation `showStatus` displays a textual snapshot of the deployers's state, which can be used to quickly find out if there is any deployable unit deployment pending, for instance, due to missing dependencies.

`org.mobicents.slee:name=CongestionControlConfiguration`::
  the MBean allows changing or retrieving the Congestion Control feature, with the container running.
  Details are provided in section <<_congestion_control_configuration>>.

IMPORTANT: For further information about JAIN SLEE 1.1 MBeans and their operations refer to the JAIN SLEE 1.1 Specification, all are covered with great detail.

[[_management_web_console]]
=== SLEE Management Console

The JMX Console is simple but the MBeans operations were made considering its invocation by management clients, not people using browsers.
The SLEE Management Console is a web application that provides high level management functionality for the SLEE, and comes pre-deployed in SLEE binary releases.
To access this console point a web browser to `http://ip:8080/slee-management-console`, where `ip` is the IP/Host the container is bound.
Unless set during start up, the IP/Host will be `127.0.0.1/localhost` by default.

Full documentation for this management tool can be found in [path]_docs/tools/slee-management-console_ directory.

[[_management_twiddle_cli]]
=== TWIDDLE CLI

Console is graphic(web) based tools.
Some deployments may require command line access to {this-platform}.
To aid such cases, {this-platform}  offers `TWIDDLE` based CLI.
It allows to manage single instance (remote or local) of {this-platform}   server. 

{this-platform} JAIN SLEE binary release includes a TWIDDLE CLI in [path]_tools/twiddle_, with standalone documentation on same path, but inside [path]_docs_ directory.

Connecting the Twiddle CLI using JMX to the JSLEE running in the same VM can be achieved as follows: 

----
./twiddle.sh --server=service:jmx:remote+http://localhost:9990 activity -l --contexts=true
----
