= Logging, Traces and Alarms

[[_log4j_service]]
== Logging Service

In {this-platform} JAIN SLEE `WildFly Logging subsystem` is used for logging. If you are not familiar with the Logging subsystem and would like to use it in your applications, you can read more about it here: https://docs.jboss.org/author/display/WFLY10/Logging+Configuration/[WildFly 10 documentation].

Logging is controlled from a [path]_/standalone/configuration/standalone.xml_ file.

The overall server logging configuration is represented by the `logging subsystem`. It consists of four notable parts: `handler` configurations, `logger`, the `root logger` declarations (aka log categories) and `logging profiles`. Each logger does reference a handler (or set of handlers). Each handler declares the log format and output:

[source,xml]
----
<subsystem xmlns="urn:jboss:domain:logging:3.0">
   <console-handler name="CONSOLE" autoflush="true">
       <level name="DEBUG"/>
       <formatter>
           <named-formatter name="COLOR-PATTERN"/>
       </formatter>
   </console-handler>
   <periodic-rotating-file-handler name="FILE" autoflush="true">
       <formatter>
           <named-formatter name="PATTERN"/>
       </formatter>
       <file relative-to="jboss.server.log.dir" path="server.log"/>
       <suffix value=".yyyy-MM-dd"/>
   </periodic-rotating-file-handler>
   <logger category="com.arjuna">
       <level name="WARN"/>
   </logger>
   [...]
   <root-logger>
       <level name="DEBUG"/>
       <handlers>
           <handler name="CONSOLE"/>
           <handler name="FILE"/>
       </handlers>
   </root-logger>
   <formatter name="PATTERN">
       <pattern-formatter pattern="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"/>
   </formatter>
   <formatter name="COLOR-PATTERN">
       <pattern-formatter pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"/>
   </formatter>
</subsystem>
----

By default Restcomm JAIN SLEE inherits level of INFO from root-logger. To make platform add
more detailed logs, file [path]_/standaloneconfiguration/standalone.xml_ has to be altered. Explicit category definition for Restcomm JAIN SLEE looks like:

[sources,xml]
----
<logger category="org.mobicents.slee">
    <level name="INFO"/>
</logger>
----

This limits the level of logging to INFO for all Restcomm JAIN SLEE classes. It is possible to declare more categories with different level, to provide logs with greater detail.

Handlers are used to determine what happens with a log message if the logger determines the message is loggable. You can read about handlers in https://docs.jboss.org/author/display/WFLY10/Handlers[Logging Handlers].

WildFly Logging subsystem supports per-deployment logging that allows you to add a logging configuration file to your deployment and have the logging for that deployment configured according to the configuration file. In an EAR the configuration should be in the META-INF directory. In a WAR or JAR deployment the configuration file can be in either the META-INF or WEB-INF/classes directories. More details you can read in https://docs.jboss.org/author/display/WFLY10/Logging+Configuration#LoggingConfiguration-PerdeploymentLogging[Per-deployment Logging].


== Alarm Facility

The `JAIN SLEE Alarm Facility` is used by SBBs, Resource Adaptors, and Profiles to request the SLEE to raise or clear alarms.
If a request is made to raise an alarm and the identified alarm has not already been raised, the alarm is raised and a corresponding alarm notification is generated by the `AlarmMBean`.
If a request is made to clear an alarm and the identified alarm is currently raised, the alarm is cleared and a corresponding alarm notification is generated by the `AlarmMBean`.

Alarm notifications are intended for consumption by management clients external to the SLEE.
The management client is responsible for registering to receive alarm notifications generated by the Alarm Facility through the external management interface of the `Alarm Facility`.
The management client may optionally provide notification filters so that only the alarm notifications that the management client would like to receive are transmitted to the management client.

For further information on how to use `JAIN SLEE Alarm Facility` and receive JMX notifications refer to the JAIN SLEE 1.1 Specification.

== Trace Facility

Notification sources such as SBBs, Resource Adaptors, Profiles, and SLEE internal components can use the `Trace Facility` to generate trace messages intended for consumption by external management clients.
Management clients register to receive trace messages generated by the `Trace Facility` through the external management interface (MBean). Filters can be applied, in a similar way as in case of Alarms.

Within the SLEE, notification sources use a `tracer` to emit trace messages.
A tracer is a named entity.
Tracer names are case-sensitive and follow the Java hierarchical naming conventions.
A tracer is considered to be an ancestor of another tracer if its name followed by a dot is a prefix of the descendant tracer`'s name.
A tracer is considered to be a parent of a tracer if there are no ancestors between itself and the descendant tracer.
For example, the tracer named `com` is the parent tracer of the tracer named `com.foo` and an ancestor of the tracer named `com.foo.bar`.

All tracers are implicitly associated with a notification source, which identifies the object in the SLEE that is emitting the trace message and is included in trace notifications generated by the `Trace MBean` on behalf of the tracer.
For instance, an SBB notification source is composed by the SBB id and the Service id.

IMPORTANT: Multiple notification sources may have tracers with same name in SLEE.
Comparing with common logging frameworks, this would mean that the notification source would be part of the log category or name.

For further information on how to use `JAIN SLEE Trace Facility` and receive JMX notifications refer to the JAIN SLEE 1.1 Specification.

[[_tracers_vs_log4j]]
=== JAIN SLEE Tracers and Log4j

{this-platform} JAIN SLEE Tracers additionally log messages to [app]`Apache Log4j`, being the log4j category, for notification source `X`, defined as `javax.slee.` concatenated with the `X.toString()`.

For instance, the full log4j logger `name` for tracer named `GoogleTalkBotSbb`, of sbb notification source with `SbbID[name=GoogleTalkBotSbb,vendor=restcomm,version=1.0]` and `ServiceID[name=GoogleTalkBotService,vendor=restcomm,version=1.0]`, would be `javax.slee.SbbNotification[service=ServiceID[name=GoogleTalkBotService, vendor=restcomm,version=0.1], sbb=SbbID[name=GoogleTalkBotSbb,vendor=restcomm, version=0.1]].GoogleTalkBotSbb` (without the spaces or breaks), which means a log4j category defining its level as `DEBUG` could be:

[source,xml]
----

<category
	name="javax.slee.SbbNotification[service=ServiceID[name=GoogleTalkBotService,
	vendor=restcomm,version=0.1],sbb=SbbID[name=GoogleTalkBotSbb,
	vendor=restcomm,version=0.1]]"> 
    <priority value="DEBUG" /> 
</category>
----

The relation of JAIN SLEE `tracers` and log4j `loggers` goes beyond log4j showing tracer's messages, changing the tracer's log4j logger `effective level` changes the tracer level in SLEE, and vice-versa.
Since JAIN SLEE tracer levels differ from log4j logger levels a mapping is needed:

.Mapping JAIN SLEE Tracer Levels with Apache Log4j Logger Levels
[cols="1,1", frame="all", options="header"]
|===
| Tracer Level | Logger Level
| OFF | OFF
| SEVERE | ERROR
| WARNING | WARN
| INFO | INFO
| CONFIG | INFO
| FINE | DEBUG
| FINER | DEBUG
| FINEST | TRACE
|===
