
= EventContext Factory Configuration

The EventContext Factory is responsible for managing all EventContexts in the SLEE Container, and its behavior is configurable.

The EventContext Factory configuration can be changed through an XML element <mbean> and a JMX MBean.

== EventContext Factory Persistent Configuration

JAIN SLEE is deployed as {jee-platform} extension and is configured through an standalone.xml. This file is located at [path]_$JBOSS_HOME/standalone/configuration_.

The configuration is exposed a JBoss Microcontainer Bean:

[source,xml]
----
<mbean name="EventContextFactoryConfiguration">
	<property name="defaultEventContextSuspensionTimeout" value="60000" />
</mbean>
----

.EventContext Factory Bean Configuration
[cols="1,1,1", frame="all", options="header"]
|===
| Property Name | Property Type | Description
| defaultEventContextSuspensionTimeout | int | defines the default timeout applied when suspending delivery of an EventContext
|===

== EventContext Factory JMX Configuration

Through JMX the EventContext Factory module configuration can be changed with the container running.
Note that such configuration changes are not persisted.

The JMX MBean which can be used to change the EventContext Factory configuration is named [app]`org.mobicents.slee:name=EventContextFactoryConfiguration`, and provides getters and setters to change each property defined in the persistent configuration.

The JConsole can be used to use this MBean, see <<_management_jconsole>>
