
= Timer Facility Configuration

The JAIN SLEE Timer Facility is the module responsible for managing SLEE timers, and the number of threads it uses is configurable.

The Timer Facility configuration can be changed through an XML file and a JMX MBean.

== Timer Facility Persistent Configuration

JAIN SLEE is deployed as {jee-platform} extension and is configured through an standalone.xml. This file is located at [path]_$JBOSS_HOME/standalone/configuration_.

The configuration is exposed a JBoss Microcontainer Bean:

[source,xml]
----
<mbean name="TimerFacilityConfiguration">
	<property name="timerThreads" value="4" />
</mbean>
----

.JAIN SLEE Timer Facility Bean Configuration
[cols="1,1,1", frame="all", options="header"]
|===
| Property Name | Property Type | Description
| timerThreads | int | defines how many threads should be used by the Timer Facility
| purgePeriod | int | defines the period (in minutes) of purging canceled tasks from the Timer Facility. Use 0 for no purge at all.
|===

== Timer Facility JMX Configuration

Through JMX the Timer Facility module configuration can be changed with the container running.
Note that such configuration changes are not persisted.

The JMX MBean which can be used to change the Timer Facility configuration is named [app]`org.mobicents.slee:name=TimerFacilityConfiguration`, and provides getters and setters to change each property defined in the persistent configuration.

The JConsole can be used to use this MBean, see <<_management_jconsole>>.
