:project-version: 5

= Install Alternatives

Binary Release::
  The binary release is a zip file containing an already built binary release of Restcomm JAIN SLEE

Release Source Building::
  As an alternative to the binary release, it is possible to download a specific release source code and build a binary from it.

Master Source Building::
  Similar as the Release Source Building, but done on the master (current development) source code.

Binary Release Snapshot::
  The binary release snapshot is a build of the master source code done daily and upoaded to a public web site.

[[_binary_release]]
== Binary Release

You can download the Binary zip files from https://mobicents.ci.cloudbees.com/job/Restcomm-JAIN-SLEE-7-Release/lastSuccessfulBuild/artifact/release/.


In this form of installation, simply unzip the downloaded zip file to the directory of your choice on any operating system that supports the zip format.

. Unzip the release file
+
Unzip the file to extract the archive contents into the location of your choice.
You can do this using the JDK jar tool (or any other ZIP extraction tool). In the example below we are assuming you downloaded the zip file was named restcomm-slee-{project-version}-wildfly-10.1.0.Final.zip to the /restcomm directory.
+

[source,subs="attributes"]
----
[usr]$ cd /restcomm
[usr]$ jar -xvf restcomm-slee-{project-version}-wildfly-10.1.0.Final.zip
----

. Setting up JBOSS_HOME Environment Variable
+
You should now have a directory called restcomm-slee-{project-version}-wildfly-10.1.0.Final.
Next you need to set your JBOSS_HOME environment variables.
This is discussed in <<_jboss_home_setup>>.


== Binary Release Snapshot

You can download the Binary Snapshot zip files from https://github.com/RestComm/jain-slee/releases/latest.
The installation is similar to the <<_binary_release>> one.

[[_release_source_building]]
== Release Source Building

. Downloading the source code
+
IMPORTANT: Git is used to manage Restcomm JAIN SLEE source code.
Instructions for downloading, installing and using Git can be found at http://git-scm.com/
+
Use Git to checkout the specific release source, the Git repository URL is https://github.com/RestComm/jain-slee/, then switch to the specific release version, lets consider {project-version}.
+
[source,subs="attributes"]
----
[usr]$ git clone https://github.com/RestComm/jain-slee restcomm-jain-slee-release
[usr]$ cd restcomm-jain-slee-release
[usr]$ git checkout tags/{project-version}
[usr]$ cd release
----

. Building the source code
+
IMPORTANT: Apache Ant 1.6 (or higher) and Maven 2.0.9 (or higher) is used to build the release.
Instructions for using Ant and Maven2, including install, can be found at http://ant.apache.org and http://maven.apache.org
+
Use Ant to build the binary.
+
[source]
----
[usr]$ ant
----
+
Once the process finishes you should have a restcomm-slee-{project-version}.zip file, installation is the same as for <<_binary_release>>.


== Master Source Building

Similar process as for <<_release_source_building>>, the only change is the Git reference should be the `master`.
The `git checkout tags/{project-version}` command should not be performed.
If already performed, the following should be used in order to switch back to the master:

[source]
----
[usr]$ git checkout master
----
