//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:43:58 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee11.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "index-hint")
public class IndexHint {

    @XmlAttribute(name = "query-operator", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String queryOperator;
    @XmlAttribute(name = "collator-ref")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String collatorRef;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the queryOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryOperator() {
        return queryOperator;
    }

    /**
     * Sets the value of the queryOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryOperator(String value) {
        this.queryOperator = value;
    }

    /**
     * Gets the value of the collatorRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollatorRef() {
        return collatorRef;
    }

    /**
     * Sets the value of the collatorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollatorRef(String value) {
        this.collatorRef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
