//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:43:58 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee11.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "profileAbstractClassName"
})
@XmlRootElement(name = "profile-abstract-class")
public class ProfileAbstractClass {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reentrant;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "profile-abstract-class-name", required = true)
    protected ProfileAbstractClassName profileAbstractClassName;

    /**
     * Gets the value of the reentrant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReentrant() {
        if (reentrant == null) {
            return "False";
        } else {
            return reentrant;
        }
    }

    /**
     * Sets the value of the reentrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReentrant(String value) {
        this.reentrant = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the profileAbstractClassName property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileAbstractClassName }
     *     
     */
    public ProfileAbstractClassName getProfileAbstractClassName() {
        return profileAbstractClassName;
    }

    /**
     * Sets the value of the profileAbstractClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileAbstractClassName }
     *     
     */
    public void setProfileAbstractClassName(ProfileAbstractClassName value) {
        this.profileAbstractClassName = value;
    }

}
