/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:44:00 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "resourceAdaptorName",
    "resourceAdaptorVendor",
    "resourceAdaptorVersion",
    "resourceAdaptorTypeRef",
    "resourceAdaptorClasses"
})
@XmlRootElement(name = "resource-adaptor")
public class ResourceAdaptor {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "resource-adaptor-name", required = true)
    protected ResourceAdaptorName resourceAdaptorName;
    @XmlElement(name = "resource-adaptor-vendor", required = true)
    protected ResourceAdaptorVendor resourceAdaptorVendor;
    @XmlElement(name = "resource-adaptor-version", required = true)
    protected ResourceAdaptorVersion resourceAdaptorVersion;
    @XmlElement(name = "resource-adaptor-type-ref", required = true)
    protected ResourceAdaptorTypeRef resourceAdaptorTypeRef;
    @XmlElement(name = "resource-adaptor-classes")
    protected ResourceAdaptorClasses resourceAdaptorClasses;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the resourceAdaptorName property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorName }
     *     
     */
    public ResourceAdaptorName getResourceAdaptorName() {
        return resourceAdaptorName;
    }

    /**
     * Sets the value of the resourceAdaptorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorName }
     *     
     */
    public void setResourceAdaptorName(ResourceAdaptorName value) {
        this.resourceAdaptorName = value;
    }

    /**
     * Gets the value of the resourceAdaptorVendor property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorVendor }
     *     
     */
    public ResourceAdaptorVendor getResourceAdaptorVendor() {
        return resourceAdaptorVendor;
    }

    /**
     * Sets the value of the resourceAdaptorVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorVendor }
     *     
     */
    public void setResourceAdaptorVendor(ResourceAdaptorVendor value) {
        this.resourceAdaptorVendor = value;
    }

    /**
     * Gets the value of the resourceAdaptorVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorVersion }
     *     
     */
    public ResourceAdaptorVersion getResourceAdaptorVersion() {
        return resourceAdaptorVersion;
    }

    /**
     * Sets the value of the resourceAdaptorVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorVersion }
     *     
     */
    public void setResourceAdaptorVersion(ResourceAdaptorVersion value) {
        this.resourceAdaptorVersion = value;
    }

    /**
     * Gets the value of the resourceAdaptorTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorTypeRef }
     *     
     */
    public ResourceAdaptorTypeRef getResourceAdaptorTypeRef() {
        return resourceAdaptorTypeRef;
    }

    /**
     * Sets the value of the resourceAdaptorTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorTypeRef }
     *     
     */
    public void setResourceAdaptorTypeRef(ResourceAdaptorTypeRef value) {
        this.resourceAdaptorTypeRef = value;
    }

    /**
     * Gets the value of the resourceAdaptorClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAdaptorClasses }
     *     
     */
    public ResourceAdaptorClasses getResourceAdaptorClasses() {
        return resourceAdaptorClasses;
    }

    /**
     * Sets the value of the resourceAdaptorClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAdaptorClasses }
     *     
     */
    public void setResourceAdaptorClasses(ResourceAdaptorClasses value) {
        this.resourceAdaptorClasses = value;
    }

}
