//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 04:43:59 PM WET 
//


package org.mobicents.slee.container.component.deployment.jaxb.slee11.sbb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "profileSpecAliasRef",
    "getProfileCmpMethodName"
})
@XmlRootElement(name = "get-profile-cmp-method")
public class GetProfileCmpMethod {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected Description description;
    @XmlElement(name = "profile-spec-alias-ref", required = true)
    protected ProfileSpecAliasRef profileSpecAliasRef;
    @XmlElement(name = "get-profile-cmp-method-name", required = true)
    protected GetProfileCmpMethodName getProfileCmpMethodName;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the profileSpecAliasRef property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileSpecAliasRef }
     *     
     */
    public ProfileSpecAliasRef getProfileSpecAliasRef() {
        return profileSpecAliasRef;
    }

    /**
     * Sets the value of the profileSpecAliasRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileSpecAliasRef }
     *     
     */
    public void setProfileSpecAliasRef(ProfileSpecAliasRef value) {
        this.profileSpecAliasRef = value;
    }

    /**
     * Gets the value of the getProfileCmpMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link GetProfileCmpMethodName }
     *     
     */
    public GetProfileCmpMethodName getGetProfileCmpMethodName() {
        return getProfileCmpMethodName;
    }

    /**
     * Sets the value of the getProfileCmpMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetProfileCmpMethodName }
     *     
     */
    public void setGetProfileCmpMethodName(GetProfileCmpMethodName value) {
        this.getProfileCmpMethodName = value;
    }

}
